# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help4vzl', '0002_auto_20180710_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y'),
        ),
    ]
