# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help4vzl', '0004_auto_20180724_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cases',
            new_name='Case',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
