# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help4vzl', '0007_postulation_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APROVED', 'Aproved'), ('REJECTED', 'Rejected')], default='NEW', max_length=10),
        ),
    ]
