# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-17 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help4vzl', '0008_auto_20180907_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='doraly94@hotmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
