# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help4vzl', '0012_auto_20180926_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
